/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AdminIglesiaRouteImport } from './routes/admin-iglesia'
import { Route as SuperAdminRouteImport } from './routes/super-admin'
import { Route as CSlugRouteImport } from './routes/c.$slug'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIglesiaRoute = AdminIglesiaRouteImport.update({
  id: '/admin-iglesia',
  path: '/admin-iglesia',
  getParentRoute: () => rootRouteImport,
} as any)
const SuperAdminRoute = SuperAdminRouteImport.update({
  id: '/super-admin',
  path: '/super-admin',
  getParentRoute: () => rootRouteImport,
} as any)
const CSlugRoute = CSlugRouteImport.update({
  id: '/c/$slug',
  path: '/c/$slug',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin-iglesia': typeof AdminIglesiaRoute
  '/super-admin': typeof SuperAdminRoute
  '/c/$slug': typeof CSlugRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/admin-iglesia': typeof AdminIglesiaRoute
  '/super-admin': typeof SuperAdminRoute
  '/c/$slug': typeof CSlugRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin-iglesia': typeof AdminIglesiaRoute
  '/super-admin': typeof SuperAdminRoute
  '/c/$slug': typeof CSlugRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/admin-iglesia' | '/super-admin' | '/c/$slug'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/admin-iglesia' | '/super-admin' | '/c/$slug'
  id: '__root__' | '/' | '/admin-iglesia' | '/super-admin' | '/c/$slug'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminIglesiaRoute: typeof AdminIglesiaRoute
  SuperAdminRoute: typeof SuperAdminRoute
  CSlugRoute: typeof CSlugRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin-iglesia': {
      id: '/admin-iglesia'
      path: '/admin-iglesia'
      fullPath: '/admin-iglesia'
      preLoaderRoute: typeof AdminIglesiaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/super-admin': {
      id: '/super-admin'
      path: '/super-admin'
      fullPath: '/super-admin'
      preLoaderRoute: typeof SuperAdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/c/$slug': {
      id: '/c/$slug'
      path: '/c/$slug'
      fullPath: '/c/$slug'
      preLoaderRoute: typeof CSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminIglesiaRoute: AdminIglesiaRoute,
  SuperAdminRoute: SuperAdminRoute,
  CSlugRoute: CSlugRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
